### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by SkyTreasure** [adgvcxz/CardLayoutManager#1]
Hi in CompileSDKVersion 26
 compile 'com.android.support:appcompat-v7:26.1.0'
 compile 'com.android.support:cardview-v7:26.1.0' getting nullpointer exception. 

` Process: com.adgvcxz.recycler, PID: 14071
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(int)' on a null object reference
                                                                          at com.adgvcxz.cardlayoutmanager.CardLayoutManager.fillChild(CardLayoutManager.java:194)
                                                                          at com.adgvcxz.cardlayoutmanager.CardLayoutManager.fill(CardLayoutManager.java:150)
                                                                          at com.adgvcxz.cardlayoutmanager.CardLayoutManager.onItemsChanged(CardLayoutManager.java:488)`

**Comment by adgvcxz** [comment]
@SkyTreasure thanks for reporting! It has been fixed
```
compile 'com.github.adgvcxz:cardlayoutmanager:0.1.1'

**Comment by adgvcxz** [comment]
@SkyTreasure 
But now jitpack does not support `com.android.tools.build:gradle:3.0`.
So I can not upload to jitpack.

**Comment by SkyTreasure** [comment]
@adgvcxz Thanks for fixing the issue :).  Have one more question. 

I tried adding Google Ads as one of the view, ad gets loaded but view is not displayed. Any idea why?

**Comment by adgvcxz** [comment]
@SkyTreasure Thanks, I'll test it as soon as possible
